server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qmzy
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.xiang.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
